# Generated by Django 3.0 on 2019-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='text',
            field=models.TextField(max_length=40),
        ),
    ]
