# Generated by Django 3.0 on 2019-12-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191216_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myform',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
